services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: find_me_api
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    container_name: find_me_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: find_me
      POSTGRES_USER: find_me_user
      POSTGRES_PASSWORD: find_me_password
    ports:
      - "5433:5432"
    volumes:
      - find_me_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: find_me_redis
    restart: unless-stopped
    ports:
      - "6380:6379"

volumes:
  find_me_postgres_data: